delivery/urls.py
from django.contrib import admin
from django.contrib.auth.views import (LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path, include
from django.views.generic import TemplateView


class LogoutConfirmView(TemplateView):
    template_name = 'registration/logout.html'


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


urlpatterns = [
    # Other URL patterns
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutConfirmView.as_view(), name='logout'),
    path('logged_out/', LogoutView.as_view(), name='logged_out'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('admin/', admin.site.urls),
    path('business/', include('business.urls')),
    path('', include('service.urls'))
]

service/urls.py
from django.urls import path, include

from .views import (
    ReviewListView, OrderListView, ExpenseListView, CustomerListView, DashboardView,
    OrderCreateView, ExpenseCreateView, OrderSuccessView, OrderDeleteView, CustomerDeleteView, SupportVIew,
    ExpenseDeleteView, ExpenseUpdateView, OrderCompleteUpdateView, OrderCancelUpdateView
)

app_name = 'service'

customer_patterns = [
    path('', CustomerListView.as_view(), name='customer_list'),
    path('<str:customer_id>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),
]
order_patterns = [
    path('', OrderListView.as_view(), name='order_list'),
    path('new/', OrderCreateView.as_view(), name='add_order'),
    path('success/', OrderSuccessView.as_view(), name='order_success'),
    path('<order_id>/delete', OrderDeleteView.as_view(), name='order_delete'),
    path('<order_id>/complete', OrderCompleteUpdateView.as_view(), name='order_complete'),
    path('<order_id>/cancel', OrderCancelUpdateView.as_view(), name='order_cancel'),
]
expense_patterns = [
    path('', ExpenseListView.as_view(), name='expense-list'),
    path('new/', ExpenseCreateView.as_view(), name='expense_add'),
    path('<str:expense_id>/update/', ExpenseUpdateView.as_view(), name='expense_update'),
    path('<str:expense_id>/delete/', ExpenseDeleteView.as_view(), name='expense_delete'),
]
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('orders/', include(order_patterns)),
    path('expenses/', include(expense_patterns)),
    path('reviews/', ReviewListView.as_view(), name='review_list'),
    path('customers/', include(customer_patterns)),
    path('support/', SupportVIew.as_view(), name='support')
]

business/models/staff.py
from django.db import models
from django.db.models import Sum

from utils import generate_id


class Staff(models.Model):
    ROLE_CHOICES = (
        ('User', 'User'),
        ('Rider', 'Rider'),
        ('Staff', 'Staff'),
    )
    profile_image = models.ImageField(upload_to='images/profileImage', blank=True, null=True)
    staff_id = models.CharField(max_length=20, unique=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()
    address = models.CharField(max_length=255)
    state_of_origin = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    emergency_contact = models.CharField(max_length=15)
    start_date = models.DateField()
    position = models.CharField(max_length=100)
    pay_rate = models.DecimalField(max_digits=10, decimal_places=2)
    bank_details = models.TextField()
    # bank_name = models.CharField(max_length=50)
    # account_number = models.CharField(max_length=255)
    # account_name = models.CharField(max_length=100)
    vehicle_type = models.CharField(max_length=100, blank=True, null=True)
    vehicle_reg_number = models.CharField(max_length=100, blank=True, null=True)
    insurance_details = models.CharField(max_length=255, blank=True, null=True)
    driver_license = models.CharField(max_length=100, blank=True, null=True)
    staff_agreement = models.FileField(upload_to='documents/staff_agreements/', blank=True, null=True)
    verification_document = models.FileField(upload_to='documents/verification_documents/', blank=True, null=True)

    @property
    def total_earning(self):
        # This will return the total amount as a number, or 0 if there are no orders
        total = self.order_set.aggregate(total_amount=Sum('amount'))['total_amount']
        return total or 0  # Return 0 if total is None (e.g., no orders)

    @property
    def total_expenses(self):
        # This will return the total amount as a number, or 0 if there are no expenses
        total = self.expense_set.aggregate(total_amount=Sum('amount'))['total_amount']
        return total or 0  # Return 0 if total is None (e.g., no expenses)

    @property
    def total_trips(self):
        return self.order_set.count()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk:  # Only set a new value on creation
            self.staff_id = generate_id()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Staff'





class Activity(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=50)
    description = models.TextField()

service/models.py
from django.db import models

# Create your models here.

service/models/expense.py
from django.db import models

from business.models import Staff
from utils import generate_id


def switch_color(value):
    match value:
        case "Paid'":
            return "green"
        case 'Pending':
            return "yellow"
        case 'Reimbursed':
            return "red"


class Expense(models.Model):
    CATEGORY_CHOICES = [
        ('Fuel', 'Fuel'),
        ('Maintenance', 'Maintenance'),
        ('Packaging', 'Packaging'),
        ('Ticket', 'Ticket'),
        ('Rider', 'Rider Fee'),
        ('Others', 'Others'),
    ]
    staff = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True, blank=True)
    expense_id = models.CharField(max_length=20, unique=True)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    name = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    vendor = models.CharField(max_length=255, blank=True, null=True)
    payment_method = models.CharField(max_length=50, blank=True, null=True, default='Cash', choices=[
        ('Cash', 'Cash'),
        ('Bank Transfer', 'Bank Transfer'),
        ('Card', 'Card'),
    ])
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, default='Pending', blank=True, null=True, choices=[
        ('Paid', 'Paid'),
        ('Pending', 'Pending'),
        ('Reimbursed', 'Reimbursed'),
    ])

    @property
    def status_color(self):
        return switch_color(self.status)

    def save(self, *args, **kwargs):
        if not self.pk:  # Only set a new value on creation
            self.expense_id = generate_id()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.expense_id

    class Meta:
        ordering = ('-date',)

service/forms/customer.py
from django import forms

from service.models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['customer_name', 'contact']

service/forms/expense.py
from django import forms

from service.models import Expense


class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['name', 'amount', 'vendor', 'category', ]

service/forms/order.py
from django import forms

from service.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['order_type', 'from_location', 'to_location', 'description', 'amount', 'to_location', 'customer']

business/views/staff.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView

from business.models import Staff


class StaffCreateView(LoginRequiredMixin, CreateView):
    model = Staff
    template_name = 'business/staff/add_staff.html'  # Specify your template
    fields = [
        'role', 'name', 'phone_number', 'email', 'address',
        'state_of_origin', 'date_of_birth', 'emergency_contact',
        'start_date', 'position', 'pay_rate', 'bank_details',
        'vehicle_type', 'vehicle_reg_number', 'insurance_details',
        'driver_license', 'staff_agreement', 'verification_document'
    ]
    success_url = reverse_lazy('business:staff_list')  # Redirect to a staff list view after creation


class StaffListView(LoginRequiredMixin, ListView):
    model = Staff
    template_name = 'business/staff/staff.html'
    context_object_name = 'staff_list'


class StaffDetailView(LoginRequiredMixin, DetailView):
    model = Staff
    template_name = 'business/staff/profile.html'
    slug_url_kwarg = 'staff_id'
    slug_field = 'staff_id'
    context_object_name = 'staff'


class StaffDeleteView(LoginRequiredMixin, DeleteView):
    model = Staff
    template_name = 'business/staff/delete.html'
    slug_url_kwarg = 'staff_id'
    success_url = reverse_lazy('business:staff_list')
    slug_field = 'staff_id'


class StaffUpdateView(LoginRequiredMixin, UpdateView):
    model = Staff
    template_name = 'business/staff/Update.html'
    pk_url_kwarg = 'staff_id'
    success_url = reverse_lazy('business:staff_list')
    slug_field = 'staff_id'

service/views.py
from django.shortcuts import render

# Create your views here.

service/views/customers.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, FormView, DeleteView

from service.forms import CustomerForm
from service.models import Customer


class CustomerListView(LoginRequiredMixin, ListView):
    model = Customer
    template_name = 'service/customer_list.html'
    context_object_name = 'customers'


class CustomerDeleteView(LoginRequiredMixin, DeleteView):
    model = Customer
    template_name = 'service/customer_delete.html'
    context_object_name = 'customer'
    slug_field = 'customer_id'
    slug_url_kwarg = 'customer_id'


class RegistrationView(FormView):
    form_class = CustomerForm
    template_name = 'service/registration_form.html'
    success_url = reverse_lazy('success')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

service/views/expenses.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from service.filters import ExpenseFilter
from service.forms import ExpenseForm
from service.models import Expense


class ExpenseListView(LoginRequiredMixin, FilterView):
    template_name = 'service/expense/expense.html'
    model = Expense
    context_object_name = 'expenses'
    filterset_class = ExpenseFilter


class ExpenseUpdateView(LoginRequiredMixin, UpdateView):
    model = Expense
    success_url = reverse_lazy('service:expense-list')
    slug_field = 'expense_id'
    slug_url_kwarg = 'expense_id'
    template_name = 'service/expense/expense_update.html'
    fields = ['name', 'amount', 'category', 'vendor', 'status']


class ExpenseDeleteView(LoginRequiredMixin, DeleteView):
    model = Expense
    success_url = reverse_lazy('service:expense-list')
    slug_field = 'expense_id'
    slug_url_kwarg = 'expense_id'
    template_name = 'service/expense/expense_delete.html'


class ExpenseCreateView(LoginRequiredMixin, CreateView):
    model = Expense
    form_class = ExpenseForm
    template_name = 'service/expense/add_expense.html'
    success_url = reverse_lazy('service:dashboard')

service/views/orders.py
from business.models import Staff
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, DeleteView, UpdateView
from django_filters.views import FilterView

from service.filters import OrderFilter
from service.forms import OrderForm, CustomerForm
from service.models import Order, Customer


class OrderCreateView(LoginRequiredMixin, CreateView):
    template_name = 'service/order/add_order.html'
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('service:order_success')  # Redirect after order is added

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Include Customer form in the context
        context['customer_form'] = CustomerForm()
        return context

    def post(self, request, *args, **kwargs):
        # Instantiate the order form and customer form with POST data
        order_form = OrderForm(request.POST)
        customer_form = CustomerForm()

        if order_form.is_valid():

            # Get the phone number from the customer form
            phone_number = request.POST['contact']
            # phone_number = customer_form.cleaned_data.get('contact')

            # Check if customer with this phone number already exists
            existing_customer = Customer.objects.filter(contact=phone_number).first()

            if existing_customer:
                # If the customer exists, associate this order with the existing customer
                order = order_form.save(commit=False)  # Save order without committing yet
                order.customer = existing_customer  # Associate order with the existing customer
                order.save()  # Save the order
                return redirect(self.success_url)  # Redirect to success page

            else:
                # If no customer exists, save the new customer and the order
                customer_form = CustomerForm(request.POST)
                if customer_form.is_valid():
                    customer = customer_form.save()  # Save the new customer
                    order = order_form.save(commit=False)
                    order.customer = customer  # Associate the order with the new customer
                    order.save()  # Save the order
                    return redirect(self.success_url)  # Redirect to success page

        # If forms are not valid, render the page with errors
        return render(request, self.template_name, {
            'order_form': order_form,
            'customer_form': customer_form
        })


class OrderSuccessView(TemplateView):
    template_name = 'service/order/order_success.html'


class OrderListView(LoginRequiredMixin, FilterView):
    model = Order
    template_name = 'service/order/orders_list.html'
    context_object_name = 'orders'
    filterset_class = OrderFilter
    riders = Staff.objects.filter(role='Rider')
    extra_context = {'riders': riders}


class OrderDeleteView(LoginRequiredMixin, DeleteView):
    model = Order
    template_name = 'service/order/orders_delete.html'
    success_url = reverse_lazy('service:order_list')
    slug_url_kwarg = 'order_id'
    slug_field = 'order_id'


class OrderCompleteUpdateView(LoginRequiredMixin, UpdateView):
    model = Order
    template_name = 'service/order/orders_update.html'
    context_object_name = 'order'
    success_url = reverse_lazy('service:order_list')
    slug_url_kwarg = 'order_id'
    slug_field = 'order_id'
    fields = ['status', 'rider']


class OrderCancelUpdateView(LoginRequiredMixin, UpdateView):
    model = Order
    template_name = 'service/order/orders_update.html'
    context_object_name = 'order'
    success_url = reverse_lazy('service:order_list')
    slug_url_kwarg = 'order_id'
    slug_field = 'order_id'
    fields = ['status', 'cancel_reason']

service/views/review.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from service.models import Review


class ReviewListView(LoginRequiredMixin, CreateView, ListView):
    template_name = 'service/review.html'
    model = Review
    fields = ('customer', 'review')
    success_url = reverse_lazy('service:review_list')
    context_object_name = 'reviews'
    # paginate_by = 5  # Number of reviews per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()  # Include the form in the context
        return context

    def get_queryset(self):
        return Review.objects.all().order_by('-id')

service/templates/service/customer_delete.html
{% extends 'base.html' %}

{% block title %}
    - Delete {{ customer.customer_name }}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Delete">
    </form>
{% endblock %}

service/templates/service/customer_list.html
{% extends 'base.html' %}

{% block title %}
    - customers
{% endblock %}

{% block content %}

    <div class="content-wrapper-scroll">

        <!-- Content wrapper start -->
        <div class="content-wrapper">

            <!-- Row start -->
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Customers</div>
                        </div>
                        <div class="card-body">

                            <div class="table-responsive">
                                <table id="" class="customerTable table v-middle m-0">
                                    <thead>
                                    <tr>
                                        <th>Customer ID</th>
                                        <th>Customer</th>
                                        <th>Contact</th>
                                        <th>Status</th>
                                        <th>Orders</th>
                                        <th>Last Order</th>
                                        <th>Amount</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for customer in customers %}
                                        <tr>
                                            <td>
                                                {{ customer.customer_id }}
                                            </td>
                                            <td>
                                                {{ customer.customer_name }}
                                            </td>
                                            <td>{{ customer.contact }}</td>
                                            <td>
                                                <span class="badge shade-{{ customer.status_color }} min-70">{{ customer.status }}</span>
                                            </td>
                                            <td>{{ customer.order_count }}</td>
                                            <td>{{ customer.last_order_date }}</td>
                                            <td>{{ customer.amount }}</td>
                                            <td>
                                                <div class="actions">
                                                    <a href="#" class="viewRow" data-bs-toggle="modal"
                                                       data-bs-target="#viewRow">
                                                        <i class="bi bi-list text-green"></i>
                                                    </a>
                                                    <a href="{% url 'service:customer_delete' customer_id=customer.customer_id %}"
                                                       class="deleteRow">
                                                        <i class="bi bi-trash text-red"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                        <div class="modal modal-dark fade" id="viewRow" tabindex="-1"
                                             aria-labelledby="viewRowLabel"
                                             style="display: none;" aria-hidden="true">
                                            <div class="modal-dialog modal-lg modal-dialog-centered">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="viewRowLabel">Customer Details</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                                aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">

                                                        <!-- Row start -->
                                                        <div class="row">
                                                            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6 col-6">
                                                                <div class="customer-card">
                                                                    <h6>Customer Name</h6>
                                                                    <h5>{{ customer.customer_name }}</h5>
                                                                </div>
                                                            </div>
                                                            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6 col-6">
                                                                <div class="customer-card">
                                                                    <h6>Customer ID</h6>
                                                                    <h5>{{ customer.customer_id }}</h5>
                                                                </div>
                                                            </div>
                                                            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6 col-6">
                                                                <div class="customer-card">
                                                                    <h6>Contact</h6>
                                                                    <h5>{{ customer.contact }}</h5>
                                                                </div>
                                                            </div>
                                                            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6 col-6">
                                                                <div class="customer-card">
                                                                    <h6>Amount Spent</h6>
                                                                    <h5>{{ customer.amount }}</h5>
                                                                </div>
                                                            </div>
                                                            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6 col-6">
                                                                <div class="customer-card">
                                                                    <h6>Joined </h6>
                                                                    <h5>{{ customer.joined }}</h5>
                                                                </div>
                                                            </div>
                                                            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6 col-6">
                                                                <div class="customer-card">
                                                                    <h6>Coupons Used</h6>
                                                                    <h5>7</h5>
                                                                </div>
                                                            </div>
                                                            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6 col-6">
                                                                <div class="customer-card">
                                                                    <h6>Total Orders</h6>
                                                                    <h5>{{ customer.order_count }}</h5>
                                                                </div>
                                                            </div>
                                                            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6 col-6">
                                                                <div class="customer-card">
                                                                    <h6>Cancelled Orders</h6>
                                                                    <h5>{{ customer.cancelled_orders }}</h5>
                                                                </div>
                                                            </div>
                                                            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-6 col-6">
                                                                <div class="customer-card">
                                                                    <h6>Reviews</h6>
                                                                    <h5>21</h5>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <!-- Row end -->

                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-success"
                                                                data-bs-dismiss="modal">Close
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    {% empty %}

                                    {% endfor %}


                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- Row end -->

        </div>
        <!-- Content wrapper end -->


{% endblock %}

service/templates/service/staff.html
{% extends 'base.html' %}

{% block content %}

    <div class="content-wrapper-scroll">

        <!-- Content wrapper start -->
        <div class="content-wrapper">

            <!-- Row start -->
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Staffs</div>
                        </div>
                        <div class="card-body">

                            <div class="table-responsive">
                                <table id="" class="customerTable table v-middle m-0">
                                    <thead>
                                    <tr>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Role</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Action</th>
                                    </tr>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            TR33485Th
                                        </td>
                                        <td>
                                            Dolly Winters
                                        </td>
                                        <td>Rider</td>

                                        <td>dories@gmail.com</td>
                                        <td>081200384</td>

                                        <td>
                                            <div class="actions">
                                                <a href="staff-profile.php" class="viewRow" data-bs-toggle="tooltip"
                                                   data-bs-placement="top" title="View">
                                                    <i class="bi bi-eye text-green"></i>
                                                </a>
                                                <a href="#" class="deleteRow" data-bs-toggle="tooltip"
                                                   data-bs-placement="top" title="Delete">
                                                    <i class="bi bi-trash text-red"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>

                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- Row end -->

        </div>
        <!-- Content wrapper end -->
{% endblock %}