business/urls.py
from django.urls import path, include
from .views import (BusinessSettingView, StaffDeleteView, StaffDetailView, StaffListView, StaffCreateView,
                    StaffUpdateView, RolePermissionsView, UserManagementView, SecuritySettings)

app_name = 'business'

staff = [
    path('', StaffListView.as_view(), name='staff_list'),
    path('new/', StaffCreateView.as_view(), name='staff_create'),
    path('<str:staff_id>/', StaffDetailView.as_view(), name='staff_detail'),
    path('<staff_id>/delete/', StaffDeleteView.as_view(), name='staff_delete'),
    path('<staff_id>/update/', StaffUpdateView.as_view(), name='staff_update'),
]
urlpatterns = [
    path('staff/', include(staff)),
    path('role-permission/', RolePermissionsView.as_view(), name='role_permission'),
    path('user-management/', UserManagementView.as_view(), name='user_management'),
    path('security-settings/', SecuritySettings.as_view(), name='security_settings'),
    path('settings/', BusinessSettingView.as_view(), name='settings'),
]

delivery/urls.py
from django.contrib import admin
from django.contrib.auth.views import (LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path, include
from django.views.generic import TemplateView


class LogoutConfirmView(TemplateView):
    template_name = 'registration/logout.html'


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


urlpatterns = [
    # Other URL patterns
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutConfirmView.as_view(), name='logout'),
    path('logged_out/', LogoutView.as_view(), name='logged_out'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('admin/', admin.site.urls),
    path('business/', include('business.urls')),
    path('', include('service.urls'))
]

service/urls.py
from django.urls import path, include

from .views import (
    ReviewListView, OrderListView, ExpenseListView, CustomerListView, DashboardView,
    OrderCreateView, ExpenseCreateView, OrderSuccessView, OrderDeleteView, CustomerDeleteView, SupportVIew,
    ExpenseDeleteView, ExpenseUpdateView, OrderCompleteUpdateView, OrderCancelUpdateView
)

app_name = 'service'

customer_patterns = [
    path('', CustomerListView.as_view(), name='customer_list'),
    path('<str:customer_id>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),
]
order_patterns = [
    path('', OrderListView.as_view(), name='order_list'),
    path('new/', OrderCreateView.as_view(), name='add_order'),
    path('success/', OrderSuccessView.as_view(), name='order_success'),
    path('<order_id>/delete', OrderDeleteView.as_view(), name='order_delete'),
    path('<order_id>/complete', OrderCompleteUpdateView.as_view(), name='order_complete'),
    path('<order_id>/cancel', OrderCancelUpdateView.as_view(), name='order_cancel'),
]
expense_patterns = [
    path('', ExpenseListView.as_view(), name='expense-list'),
    path('new/', ExpenseCreateView.as_view(), name='expense_add'),
    path('<str:expense_id>/update/', ExpenseUpdateView.as_view(), name='expense_update'),
    path('<str:expense_id>/delete/', ExpenseDeleteView.as_view(), name='expense_delete'),
]
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('orders/', include(order_patterns)),
    path('expenses/', include(expense_patterns)),
    path('reviews/', ReviewListView.as_view(), name='review_list'),
    path('customers/', include(customer_patterns)),
    path('support/', SupportVIew.as_view(), name='support')
]

business/models/business.py
from django.db import models


class BusinessSetting(models.Model):
    business_name = models.CharField(max_length=255)
    started_date = models.DateField()
    logo = models.ImageField(upload_to='business_logos/')
    currency = models.CharField(max_length=10)
    currency_symbol_placement = models.CharField(max_length=10,
                                                 choices=[('Before', 'Before Amount'), ('After', 'After Amount')])
    business_email = models.EmailField()
    business_phone = models.CharField(max_length=20)
    business_country = models.CharField(max_length=100)
    business_state = models.CharField(max_length=100)
    business_address = models.TextField()

    def __str__(self):
        return self.business_name

    class Meta:
        verbose_name_plural = 'business setting'


class Business(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    company_name = models.CharField(max_length=100)
    email = models.EmailField(blank=True)
    password = models.CharField(max_length=128)

business/models/staff.py
from django.db import models
from django.db.models import Sum

from utils import generate_id


class Staff(models.Model):
    ROLE_CHOICES = (
        ('User', 'User'),
        ('Rider', 'Rider'),
        ('Staff', 'Staff'),
    )
    profile_image = models.ImageField(upload_to='images/profileImage', blank=True, null=True)
    staff_id = models.CharField(max_length=20, unique=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()
    address = models.CharField(max_length=255)
    state_of_origin = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    emergency_contact = models.CharField(max_length=15)
    start_date = models.DateField()
    position = models.CharField(max_length=100)
    pay_rate = models.DecimalField(max_digits=10, decimal_places=2)
    bank_details = models.TextField()
    # bank_name = models.CharField(max_length=50)
    # account_number = models.CharField(max_length=255)
    # account_name = models.CharField(max_length=100)
    vehicle_type = models.CharField(max_length=100, blank=True, null=True)
    vehicle_reg_number = models.CharField(max_length=100, blank=True, null=True)
    insurance_details = models.CharField(max_length=255, blank=True, null=True)
    driver_license = models.CharField(max_length=100, blank=True, null=True)
    staff_agreement = models.FileField(upload_to='documents/staff_agreements/', blank=True, null=True)
    verification_document = models.FileField(upload_to='documents/verification_documents/', blank=True, null=True)

    @property
    def total_earning(self):
        # This will return the total amount as a number, or 0 if there are no orders
        total = self.order_set.aggregate(total_amount=Sum('amount'))['total_amount']
        return total or 0  # Return 0 if total is None (e.g., no orders)

    @property
    def total_expenses(self):
        # This will return the total amount as a number, or 0 if there are no expenses
        total = self.expense_set.aggregate(total_amount=Sum('amount'))['total_amount']
        return total or 0  # Return 0 if total is None (e.g., no expenses)

    @property
    def total_trips(self):
        return self.order_set.count()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk:  # Only set a new value on creation
            self.staff_id = generate_id()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Staff'





class Activity(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=50)
    description = models.TextField()

business/forms.py
from django import forms

from .models import Staff, BusinessSetting


class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        exclude = ('profile_image', 'staff_id')


class BusinessSettingsForm(forms.ModelForm):
    class Meta:
        model = BusinessSetting
        fields = '__all__'

business/views/staff.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView

from business.models import Staff


class StaffCreateView(LoginRequiredMixin, CreateView):
    model = Staff
    template_name = 'business/staff/add_staff.html'  # Specify your template
    fields = [
        'role', 'name', 'phone_number', 'email', 'address',
        'state_of_origin', 'date_of_birth', 'emergency_contact',
        'start_date', 'position', 'pay_rate', 'bank_details',
        'vehicle_type', 'vehicle_reg_number', 'insurance_details',
        'driver_license', 'staff_agreement', 'verification_document'
    ]
    success_url = reverse_lazy('business:staff_list')  # Redirect to a staff list view after creation


class StaffListView(LoginRequiredMixin, ListView):
    model = Staff
    template_name = 'business/staff/staff.html'
    context_object_name = 'staff_list'


class StaffDetailView(LoginRequiredMixin, DetailView):
    model = Staff
    template_name = 'business/staff/profile.html'
    slug_url_kwarg = 'staff_id'
    slug_field = 'staff_id'
    context_object_name = 'staff'


class StaffDeleteView(LoginRequiredMixin, DeleteView):
    model = Staff
    template_name = 'business/staff/delete.html'
    slug_url_kwarg = 'staff_id'
    success_url = reverse_lazy('business:staff_list')
    slug_field = 'staff_id'


class StaffUpdateView(LoginRequiredMixin, UpdateView):
    model = Staff
    template_name = 'business/staff/Update.html'
    pk_url_kwarg = 'staff_id'
    success_url = reverse_lazy('business:staff_list')
    slug_field = 'staff_id'

business/templates/business/staff/Update.html
{% extends 'base.html' %}

{% block title %}
    - Update {{ object.name }}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="Submit" id="submit">
    </form>
{% endblock %}

business/templates/business/staff/add_staff.html
{% extends 'base.html' %}
{% block title %}
    - add staff
{% endblock %}

{% block content %}


    <div class="content-wrapper">

        <!-- Row start -->
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="card">

                    <div class="card-body">

                        <div class="row">
                            <div class="col-xl-12 col-lg-12 col-md-16 col-sm-12 col-12">
                                <div class="card-border">
                                    <div class="card-border-title">Order Information</div>
                                    <div class="card-border-body">
                                        <form method="post"  enctype="multipart/form-data">
                                            {% csrf_token %}
                                            {{ form.non_field_errors }}
                                            {% for field in form %}
                                                <div>
                                                    {{ field.label_tag }}
                                                    {{ field }}
                                                    {% for error in field.errors %}
                                                        <p class="error">{{ error }}</p>
                                                    {% endfor %}
                                                </div>
                                            {% endfor %}
                                            <button type="submit">Submit</button>
                                        </form>

                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
            <!-- Row end -->

        </div>
        <script>
            // Function to toggle the visibility of the vehicle information section based on selected role
            function toggleVehicleInfo() {
                const role = document.getElementById('role').value;
                const vehicleInfo = document.getElementById('vehicleInfo');

                if (role === 'rider') {
                    vehicleInfo.style.display = 'block';
                } else {
                    vehicleInfo.style.display = 'none';
                }
            }
        </script>
    </div>
{% endblock %}

business/templates/business/staff/bk.html
{% extends 'base.html' %}
{% block title %}
    - add staff
{% endblock %}

{% block content %}


    <div class="content-wrapper">

        <!-- Row start -->
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="card">

                    <div class="card-body">

                        <div class="row">
                            <div class="col-xl-12 col-lg-12 col-md-16 col-sm-12 col-12">
                                <div class="card-border">
                                    <div class="card-border-title">Order Information</div>
                                    <div class="card-border-body">
                                        <form id="registrationForm" method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <!-- Role Selection -->
                                            <div class="mb-4">
                                                <label for="role" class="form-label">Select Role</label>
                                                <select class="form-select" id="role" onchange="toggleVehicleInfo()"
                                                        required name="role">
                                                    <option value="" disabled selected>Select Role</option>
                                                    <option value="rider">Rider</option>
                                                    <option value="staff">Staff</option>
                                                </select>
                                            </div>

                                            <!-- Basic Information Section -->
                                            <fieldset class="border p-4 mb-4">
                                                <legend class="w-auto px-2">Basic Information</legend>

                                                <div class="mb-3">
                                                    <label for="fullName" class="form-label">Full Name</label>
                                                    <input type="text" class="form-control" id="fullName"
                                                           placeholder="Enter full name" required name="name">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="phoneNumber" class="form-label">Phone Number</label>
                                                    <input type="tel" class="form-control" id="phoneNumber"
                                                           placeholder="Enter phone number" required
                                                           name="phone_number">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="email" class="form-label">Email</label>
                                                    <input type="email" class="form-control" id="email"
                                                           placeholder="Enter email" required name="email">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="address" class="form-label">Home Address</label>
                                                    <input type="text" class="form-control" id="address"
                                                           placeholder="Enter home address" required name="address">
                                                </div>
                                                <div class="mb-3">
                                                    <label for="State of Origin" class="form-label">State Of
                                                        Origin</label>
                                                    <input type="text" class="form-control" id="address"
                                                           placeholder="Enter state of Origin" required
                                                           name="state_of_origin">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="dob" class="form-label">Date of Birth</label>
                                                    <input type="date" class="form-control" id="dob" required
                                                           name="date_of_birth">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="emergencyContact" class="form-label">Emergency
                                                        Contact</label>
                                                    <input type="text" class="form-control" id="emergencyContact"
                                                           placeholder="Enter emergency contact" required
                                                           name="emergency_contact">
                                                </div>
                                            </fieldset>

                                            <!-- Employment Information Section -->
                                            <fieldset class="border p-4 mb-4">
                                                <legend class="w-auto px-2">Employment Information</legend>


                                                <div class="mb-3">
                                                    <label for="startDate" class="form-label">Start Date</label>
                                                    <input type="date" class="form-control" id="startDate" required
                                                           name="start_date">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="position" class="form-label">Position/Role</label>
                                                    <input type="text" class="form-control" id="position"
                                                           placeholder="Enter position or role" required
                                                           name="position">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="payRate" class="form-label">Pay Rate</label>
                                                    <input type="number" class="form-control" id="payRate"
                                                           placeholder="Enter pay rate" required name="pay_rate">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="bankDetails" class="form-label">Bank Account
                                                        Details</label>
                                                    <input type="text" class="form-control" id="bankDetails"
                                                           placeholder="Enter bank account details for payroll"
                                                           required name="{{ form.bank_details.name }}">
                                                </div>
                                            </fieldset>

                                            <!-- Vehicle Information Section (Riders only) -->
                                            <fieldset class="border p-4 mb-4" id="vehicleInfo" style="display:none;">
                                                <legend class="w-auto px-2">Vehicle Information (Riders Only)</legend>

                                                <div class="mb-3">
                                                    <label for="vehicleType" class="form-label">Vehicle Type</label>
                                                    <input type="text" class="form-control" id="vehicleType"
                                                           placeholder="Enter vehicle type" required
                                                           name="vehicle_type">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="vehicleRegNumber" class="form-label">Vehicle
                                                        Registration Number</label>
                                                    <input type="text" class="form-control" id="vehicleRegNumber"
                                                           placeholder="Enter vehicle registration number" required
                                                           name="vehicle_reg_number">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="insuranceDetails" class="form-label">Insurance
                                                        Details</label>
                                                    <input type="text" class="form-control" id="insuranceDetails"
                                                           placeholder="Enter vehicle insurance details" required
                                                           name="insurance_details">
                                                </div>

                                                <div class="mb-3">
                                                    <label for="driverLicense" class="form-label">Driver’s
                                                        License</label>
                                                    <input type="text" class="form-control" id="driverLicense"
                                                           placeholder="Enter driver’s license number" required
                                                           name="driver_license">
                                                </div>
                                            </fieldset>

                                            <fieldset class="border p-4 mb-4">
                                                <legend class="w-auto px-2">Upload Documents</legend>

                                                <div class="mb-3">
                                                    <label for="staffAgreement" class="form-label">Staff Agreement
                                                        Document</label>
                                                    <input type="file" class="form-control" id="staffAgreement"
                                                           accept=".pdf,.doc,.docx" required name="staff_agreement">
                                                    <small class="form-text text-muted">Upload the staff agreement in
                                                        PDF or Word format.</small>
                                                </div>

                                                <div class="mb-3">
                                                    <label for="verificationDocument" class="form-label">Means of
                                                        Verification Document</label>
                                                    <input type="file" class="form-control" id="verificationDocument"
                                                           accept=".pdf,.doc,.docx" required
                                                           name="verification_document">
                                                    <small class="form-text text-muted">Upload a document for means of
                                                        verification (e.g., ID, certificate).</small>
                                                </div>
                                            </fieldset>


                                            <!-- Submit Button -->
                                            <button type="submit" class="btn btn-primary">Submit Registration</button>
                                        </form>

                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
            <!-- Row end -->

        </div>
        <script>
            // Function to toggle the visibility of the vehicle information section based on selected role
            function toggleVehicleInfo() {
                const role = document.getElementById('role').value;
                const vehicleInfo = document.getElementById('vehicleInfo');

                if (role === 'rider') {
                    vehicleInfo.style.display = 'block';
                } else {
                    vehicleInfo.style.display = 'none';
                }
            }
        </script>
    </div>
{% endblock %}

business/templates/business/staff/delete.html
{% extends 'base.html' %}

{% block title %}
    - delete {{ object.name }}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="Submit" id="submit">
    </form>
{% endblock %}

business/templates/business/staff/staff.html
{% extends 'base.html' %}

{% block title %}
    - Staff
{% endblock %}


{% block content %}
    <div class="content-wrapper-scroll">

        <!-- Content wrapper start -->
        <div class="content-wrapper">

            <!-- Row start -->
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Staffs</div>
                        </div>
                        <div class="card-body">

                            <div class="table-responsive">
                                <table id="" class="customerTable table v-middle m-0">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Role</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for staff in staff_list %}
                                        <tr>
                                            <td>
                                                {{ staff.staff_id }}
                                            </td>
                                            <td>
                                                {{ staff.name }}
                                            </td>
                                            <td>{{ staff.role }}</td>

                                            <td>{{ staff.email }}</td>
                                            <td>{{ staff.phone_number }}</td>

                                            <td>
                                                <div class="actions">
                                                    <a href="{% url 'business:staff_detail'  staff_id=staff.staff_id %}"
                                                       class="viewRow" data-bs-toggle="tooltip"
                                                       data-bs-placement="top" title="View">
                                                        <i class="bi bi-eye text-green"></i>
                                                    </a>
                                                    <a href="{% url 'business:staff_delete'  staff_id=staff.staff_id %}"
                                                       class="deleteRow" data-bs-toggle="tooltip"
                                                       data-bs-placement="top" title="Delete">
                                                        <i class="bi bi-trash text-red"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    {% empty %}
                                        <tr>
                                            <td>NO Staff Registered <a
                                                    href="{% url 'business:staff_create' %}" class="link link-primary">Register</a>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- Row end -->

        </div>
        <!-- Content wrapper end -->

{% endblock %}